version: '3.7'
services:
   plex:
     image: ghcr.io/linuxserver/plex:latest
     container_name: my_plex
     restart: always
     network_mode: host
     volumes:
       - :-CDATA_PATH-:/plex/config:/config
       - :-CDATA_PATH-:/plex/tvshows/:/tv
       - :-CDATA_PATH-:/plex/movies:/movies
     environment:
       - PUID=:-CDID-:
       - PGID=:-CDID-:
       - VERSION=docker

   nginx:
     image: nginx:latest
     container_name: my_nginx
     restart: always
     volumes:
       - :-CDATA_PATH-:/nginx/html:/usr/share/nginx/html
     ports:
       - 80:80

   squid_proxy:
     image: nordvpn-proxy
     container_name: my_squid_proxy
     restart: always
     privileged: true
     network_mode: host
     dns:
       - 8.8.8.8
     volumes:
       - :-CDATA_PATH-:/squid/log:/var/log/squid
     environment:
       - SERVER=ca
       - PROTOCOL=udp

#   rsyslog:
#     image: my_rsyslog:latest
#     container_name: my_rsyslog
#     restart: always
#     network_mode: host
#     volumes:
#       - :-CDATA_PATH-:/rsyslog/log:/var/log
#       - :-CDATA_PATH-:/rsyslog/rsyslog.d:/etc/rsyslog.d

